Library/Controllers/WritersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class WritersController : LibraryController
    {
        public ActionResult Index()
        {
            Models.LibraryTableAdapters.WritesTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritesTableAdapter();
            Models.Library.WritesDataTable writersTable = new Models.Library.WritesDataTable();
            writersAdapter.Fill(writersTable);
            ViewData["writers"] = writersTable.Rows;
            ViewData["title"] = "Yazarlar";
            return View();
        }
        public ActionResult Add(string error = null)
        {
            ViewData["title"] = "Yazar Ekle";
            if (error != null)
            {
                ViewData["error"] = error;
            }
            return View();
        }
        public void ProcessNewWriter(long id, string writerName, string surname, string AKA)
        {
            Models.LibraryTableAdapters.WritesTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritesTableAdapter();

            if (writerName == null)
            {
                Response.Redirect("~/writers/add");
                return;
            }
            writerName = writerName.Trim();
            if (writerName == "")
            {
                Response.Redirect("~/writers/add");
                return;
            }
            if (writerName.Length > 100)
            {
                Response.Redirect("~/writers/add");
                return;
            }
            if (surname != null)
            {
                surname = surname.Trim();
                if (surname == "")
                {
                    surname = null;
                }
                else
                {
                    if (surname.Length > 100)
                    {
                        Response.Redirect("~/writers/add");
                        return;
                    }
                }
            }
            if (AKA != null)
            {
                AKA = AKA.Trim();
                if (AKA == "")
                {
                    AKA = null;
                }
                else
                {
                    if (AKA.Length > 50)
                    {
                        Response.Redirect("~/writers/add");
                        return;
                    }
                }
            }
            try
            {
                writersAdapter.AddWriter(writerName, surname, AKA);
                Response.Redirect("~/writers");
            }
            catch
            {
                Response.Redirect("~/writers/add");
            }
        }
        public void Delete(long id)
        {
            Models.LibraryTableAdapters.WritesTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritesTableAdapter();
            writersAdapter.DeleteWriters(id);
            Response.Redirect("~/writers");
        }
        public ActionResult Update(long id)
        {
            Models.LibraryTableAdapters.WritesTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritesTableAdapter();
            Models.Library.WritesDataTable writersTable = new Models.Library.WritesDataTable();
            Models.Library.WritesRow writersRow;

            writersAdapter.FillById(writersTable, id);
            writersRow = (Models.Library.WritesRow)writersTable.Rows[0];
            ViewData["title"] = writersRow.writersName;
            ViewData["writerRow"] = writersRow;
            return View();
        }
        public void ProcessWriter(long id, string writerName, string writerSurname, string AKA)
        {
            Models.LibraryTableAdapters.WritesTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritesTableAdapter();

            if (writerName == null)
            {
                Response.Redirect("~/writers/update/" + id.ToString());
                return;
            }
            writerName = writerName.Trim();
            if (writerName == "")
            {
                Response.Redirect("~/writers/update/" + id.ToString());
                return;
            }
            if (writerName.Length > 100)
            {
                Response.Redirect("~/writers/update/" + id.ToString());
                return;
            }

            if (writerSurname != null)
            {
                writerSurname = writerSurname.Trim();
                if (writerSurname == "")
                {
                    writerSurname = null;
                }
                else
                {
                    if (writerSurname.Length > 100)
                    {
                        Response.Redirect("~/writers/update");
                        return;
                    }
                }
            }
            if (AKA != null)
            {
                AKA = AKA.Trim();
                if (AKA == "")
                {
                    AKA = null;
                }
                else
                {
                    if (AKA.Length > 50)
                    {
                        Response.Redirect("~/writers/update");
                        return;
                    }
                }
            }
            try
            {
                writersAdapter.UpdateWriter(writerName, writerSurname, AKA, id);
                Response.Redirect("~/writers");
            }
            catch
            {
                Response.Redirect("~/writers/update");
            }
        }
    }
}

Library/Views/Writers/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<form action="~/writers/processnewwriter" method="post">
    <input type="text" name="writerName" id="writerName" placeholder="Adı" data-val="true" data-val-required="Bu alan boş geçilemez!" maxlength="100" />
    <span class="field-validation-valid" data-valmsg-for="writerName" data-valmsg-replace="true"></span> <!-- valmsg-usernamein hata mesajlarını bu id de ver class hazır scriptin classı -->
    <input type="text" name="surname"  placeholder="Soyadı" maxlength="50" />
    <input type="text" name="AKA" placeholder="Mahlas" maxlength="50" />
    <input type="submit" value="TAMAM" />
</form>
@if (ViewData["error"] != null)
{
    <span>@ViewData["error"]</span>
}

Library/Views/Writers/Index.cshtml
@{
    System.Data.DataRowCollection writers = (System.Data.DataRowCollection)ViewData["writers"];
}

<link rel="stylesheet" href="~/stil.css" />
<script>
    function Delete(id) {
        if (confirm("Emin misiniz?") == true) {
            location.assign("@Url.Action("Delete", "Writers")/" + id.toString());
        }
    }
</script>
<a id="writersAdd" href="~/writers/Add">Yazar Ekle</a>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Adı Soyadı</th>
            <th>Mahlas</th>
            <th></th>
        </tr>
    </thead>

    @foreach (Library.Models.Library.WritesRow writersRow in writers)
    {
        <tr>
            <td><a href="~/writers/update/@writersRow.id.ToString()">@writersRow.id.ToString()</a></td>
            <td>
                @writersRow.writersName
                @if (writersRow.IswritersSurnameNull() == false)
                {
                    @writersRow.writersSurname
                }
            </td>
            <td>
                @if (writersRow.IswritersAkaNull() == false)
                {
                    @writersRow.writersAka
                }
            </td>
            <td><button onclick="Delete(@writersRow.id)">Sil</button></td>
        </tr>
    }
</table>

Library/Views/Writers/Update.cshtml
@{
    Library.Models.Library.WritesRow writerRow = (Library.Models.Library.WritesRow)ViewData["writerRow"];
}

<h2>Add</h2>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<form action="~/writers/processWriter" method="post">
    <input type="text" name="writerName" id="writerName" placeholder="Yazar Adı" data-val="true" data-val-required="Bu alan boş geçilemez!" maxlength="100" value="@writerRow.writersName" />
    <span class="field-validation-valid" data-valmsg-for="writerName" data-valmsg-replace="true"></span> <!-- valmsg-usernamein hata mesajlarını bu id de ver class hazır scriptin classı -->
    <input type="text" name="writerSurname" id="writerSurname" placeholder="Yazar Soyadı" maxlength="100"/>
    <input type="text" name="AKA" id="AKA" placeholder="Mahlas" maxlength="50" />
    <input type="hidden" name="id" value="@writerRow.id" />
    <input type="submit" value="TAMAM" />
</form>
@if (ViewData["error"] != null)
{
    <span>@ViewData["error"]</span>
}